### ISSUE TITLE
ModuleNotFoundError: No module named 'tomato'

### ISSUE THREAD

**Issue by VimWei** [coolcode/tomato-clock#19]
1. `$ pip install tomato-clock`
2.  `$ tomato`

```
Traceback (most recent call last):
  File "c:\users\chenwei\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\chenwei\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chenwei\AppData\Local\Programs\Python\Python39\Scripts\tomato.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'tomato'

```

**Comment by VimWei** [comment]
`tomato.py`

**Comment by AlucardNosferatu** [comment]
C:\WINDOWS\system32>tomato -t
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\tomato.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'tomato'

**Comment by AlucardNosferatu** [comment]
> C:\WINDOWS\system32>tomato -t Traceback (most recent call last): File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\tomato.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'tomato'

python tomato.py worked, but exe still has the problem of a missing module "toamto"

**Comment by AlucardNosferatu** [comment]
> > C:\WINDOWS\system32>tomato -t Traceback (most recent call last): File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\tomato.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'tomato'
> 
> python tomato.py worked, but exe still has the problem of a missing module "tomato"

Solved, tomato.py should be in the Lib but not Scripts
