### ISSUE TITLE
Suggestion for hiding `keyboardInterrupt`

### ISSUE THREAD

**Issue by 9527q** [coolcode/tomato-clock#2]
An example:

```shell
~/git/tomato-clock(master*) » ./tomato.py
🍅 tomato 25 minutes. Ctrl+C to exit
^C -------------------------------------------------- [0%] 24:59 ⏰Traceback (most recent call last):
  File "./tomato.py", line 101, in <module>
    main()
  File "./tomato.py", line 26, in main
    tomato(WORK_MINUTES, 'It is time to take a break')
  File "./tomato.py", line 63, in tomato
    time.sleep(1)
KeyboardInterrupt
```

In the front, the user see that he can exit with Ctrl + C, but after pressing Ctrl + C, program displays some error info. 

These errors are not what the user wants to see, he just wants to exit.

So it's recommended to catch `keyboardInterrupt`, and then prompt "goodbye" or "thank you" or something.

**Comment by coolcode** [comment]
> keyboardInterrupt

Nice suggestion. @9527q  I will add it into next version.

**Comment by coolcode** [comment]
@9527q  solved. 
```bash
$ ./tomato.py                                                                                                                                             
🍅 tomato 25 minutes. Ctrl+C to exit
^C -------------------------------------------------- [0%] 24:58 ⏰
👋 goodbye
```

**Comment by 9527q** [comment]
👍👍
